const orders = [
  { id: 'HC-1042', customer: 'Ananya Sharma', service: 'AC service & repair', store: 'Indiranagar', employee: 'Rahul Kumar', time: 'Today, 4–6 PM', status: 'assigned' },
  { id: 'HC-1041', customer: 'The Olive Kitchen', service: 'Kitchen equipment repair', store: 'Koramangala', employee: '', time: 'Today, 3–5 PM', status: 'pending' },
  { id: 'HC-1040', customer: 'Vivek Rao', service: 'Washing machine repair', store: 'Indiranagar', employee: 'Suresh N', time: 'Today, 2–4 PM', status: 'progress' },
  { id: 'HC-1039', customer: 'Hotel Azure', service: 'HVAC maintenance', store: 'Whitefield', employee: 'Dinesh P', time: 'Tomorrow, 9–11 AM', status: 'assigned' }
];
const roleMeta = { admin: ['COMMAND CENTER', 'Good evening, Kasireddy', 'Main administrator'], store: ['STORE OPERATIONS', 'Indiranagar store', 'Store manager'], employee: ['MY WORK', 'Hello, Rahul', 'Service professional'], customer: ['MY HOMECARE', 'Your bookings', 'Customer'] };
let role = 'admin';
const statuses = { assigned:'Assigned', pending:'Needs assignment', progress:'In progress' };
function orderRows(list, assignment = false) { return list.map(o => `<tr><td><b>${o.id}</b><small>${o.customer}</small></td><td>${o.service}<small>${o.time}</small></td><td>${o.store}</td><td>${assignment && !o.employee ? `<div class="assignment"><select id="staff-${o.id}"><option>Choose employee</option><option>Rahul Kumar</option><option>Suresh N</option><option>Dinesh P</option></select><button onclick="assign('${o.id}')">Assign</button></div>` : (o.employee || '—')}</td><td><span class="status ${o.status}">${statuses[o.status]}</span></td></tr>`).join(''); }
function adminView(){return `<section class="metric-grid"><article class="metric"><p>TODAY’S BOOKINGS</p><h2>48</h2><small>↑ 18% vs yesterday</small></article><article class="metric"><p>ACTIVE STORES</p><h2>03</h2><small>All stores online</small></article><article class="metric"><p>OPEN ASSIGNMENTS</p><h2>06</h2><small>Needs attention</small></article><article class="metric alert"><p>MONTHLY REVENUE</p><h2>₹1.28L</h2><small>Cash collection tracking</small></article></section><section class="content-grid"><article class="panel"><div class="panel-head"><h3>Live service orders</h3><a>View all →</a></div><table class="orders"><thead><tr><th>ORDER</th><th>SERVICE</th><th>STORE</th><th>PROFESSIONAL</th><th>STATUS</th></tr></thead><tbody>${orderRows(orders,true)}</tbody></table></article><article class="panel"><div class="panel-head"><h3>Store performance</h3><a>Manage →</a></div>${storeRow('⌂','Indiranagar','22 jobs today','₹48,200')}${storeRow('⌂','Koramangala','15 jobs today','₹35,800')}${storeRow('⌂','Whitefield','11 jobs today','₹27,100')}</article><article class="panel wide"><div class="panel-head"><h3>Bookings this week</h3><a>Download report →</a></div><div class="bar-chart"><i class="bar" style="height:52%"><small>Mon</small></i><i class="bar" style="height:72%"><small>Tue</small></i><i class="bar" style="height:46%"><small>Wed</small></i><i class="bar active" style="height:91%"><small>Thu</small></i><i class="bar" style="height:68%"><small>Fri</small></i><i class="bar" style="height:39%"><small>Sat</small></i><i class="bar" style="height:29%"><small>Sun</small></i></div></article></section>`}
function storeRow(icon,name,jobs,cash){return `<div class="store-row"><span class="store-icon">${icon}</span><div><b>${name}</b><small>${jobs}</small></div><strong>${cash}</strong></div>`}
function storeView(){const storeOrders=orders.filter(o=>o.store==='Indiranagar');return `<section class="metric-grid"><article class="metric"><p>TODAY’S JOBS</p><h2>22</h2><small>7 completed</small></article><article class="metric"><p>TEAM AVAILABLE</p><h2>08</h2><small>2 on a job</small></article><article class="metric alert"><p>UNASSIGNED</p><h2>02</h2><small>Assign now</small></article><article class="metric"><p>CASH DUE</p><h2>₹8,650</h2><small>Collected after service</small></article></section><section class="content-grid"><article class="panel"><div class="panel-head"><h3>Today’s store queue</h3><a>View calendar →</a></div><table class="orders"><thead><tr><th>ORDER</th><th>SERVICE</th><th>STORE</th><th>PROFESSIONAL</th><th>STATUS</th></tr></thead><tbody>${orderRows(storeOrders,true)}</tbody></table></article><article class="panel"><div class="panel-head"><h3>Team availability</h3><a>Manage staff →</a></div>${storeRow('RK','Rahul Kumar','Free after 6 PM','Available')}${storeRow('SN','Suresh N','On service HC-1040','Busy')}${storeRow('DP','Dinesh P','Free now','Available')}</article></section>`}
function employeeView(){return `<section class="metric-grid"><article class="metric"><p>JOBS TODAY</p><h2>03</h2><small>1 completed</small></article><article class="metric"><p>RATING</p><h2>4.9</h2><small>126 reviews</small></article><article class="metric"><p>THIS WEEK</p><h2>₹6,250</h2><small>Cash collected</small></article><article class="metric"><p>ON TIME</p><h2>98%</h2><small>Great work!</small></article></section><section class="content-grid"><article class="panel"><div class="panel-head"><h3>Your next service</h3><a>Open map →</a></div><div class="task-card"><b>HC-1042 · AC service & repair</b><p>Ananya Sharma · Indiranagar · Today, 4–6 PM</p><footer>Customer has chosen cash on service <button onclick="alert('Job marked as started')">Start service</button></footer></div><div class="task-card"><b>HC-1046 · Electrical inspection</b><p>Reena Menon · Indiranagar · Tomorrow, 9–11 AM</p><footer>Upcoming <button>View details</button></footer></div></article><article class="panel"><div class="panel-head"><h3>Store messages</h3><a>Open inbox →</a></div><div class="task-card"><b>Indiranagar store</b><p>Please upload AC service photos after completion.</p><footer>10 min ago</footer></div></article></section>`}
function customerView(){const saved=JSON.parse(localStorage.getItem('homecare_latest_booking')||'null');return `<section class="customer-hero"><p>QUICK BOOKING</p><h2>Need help with something?</h2><p>Verified professionals, transparent prices, and cash payment after service.</p><a href="index.html">Book a service →</a></section><section class="content-grid"><article class="panel"><div class="panel-head"><h3>Your bookings</h3><a href="index.html">Book another →</a></div>${saved?`<div class="task-card"><b>${saved.service}</b><p>${saved.slot} · ${saved.address}</p><footer>Cash on Service <span class="status assigned">Confirmed</span></footer></div>`:`<p class="empty">You have no bookings yet. Your booked services will appear here.</p>`}</article><article class="panel"><div class="panel-head"><h3>Help & support</h3></div><p class="empty">Questions about a booking? Contact your local HomeCare store.</p></article></section>`}
function render(){const [eyebrow,heading,name]=roleMeta[role];document.getElementById('headingEyebrow').textContent=eyebrow;document.getElementById('pageHeading').textContent=heading;document.getElementById('roleName').textContent=name;document.getElementById('dashboard').innerHTML={admin:adminView,store:storeView,employee:employeeView,customer:customerView}[role]();}
function assign(id){const emp=document.getElementById(`staff-${id}`).value;if(emp==='Choose employee')return;const order=orders.find(o=>o.id===id);order.employee=emp;order.status='assigned';render();alert(`${id} assigned to ${emp}. The employee and store have been notified.`)}
document.querySelectorAll('[data-role]').forEach(btn=>btn.addEventListener('click',()=>{role=btn.dataset.role;document.querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('active',b===btn));render()}));render();
